name: XMMForceFairPlay
version: '${project.version}'
main: dev.zerek.XMMForceFairPlay.XMMForceFairPlay
api-version: '26.1.2'
folia-supported: true
depend:
  - packetevents

permissions:
  fairplay.bypass:
    description: Allows players to bypass Xaero's Minimap fair-play restrictions
    default: false
